.envs: &envs
  PLATFORM_ENV: local
  NPM_CONFIG_SHELL: /bin/bash
  NPM_CONFIG_SCRIPT_SHELL: /bin/bash
  HTTP_HOST: 127.0.0.1
  NODE_ENV: production

  CORS_ORIGIN: '*'

  FRONTEND_DOMAIN: localhost
  FRONTEND_PROTOCOL: http

  API_DOMAIN: localhost
  API_PROTOCOL: http

.common: &common
  script: npm
  args: run start
  watch: true
  ignore_watch: [node_modules, dist]
  watch_options:
    followSymlinks: true
  env:
    <<: *envs
apps:
  - name: app
    <<: *common
    watch: false
    namespace: frontend
    cwd: ./clients/web-app
    env_file: ./clients/web-app/.env
    env:
      <<: *envs
      PORT: 3000

  - name: api
    <<: *common
    namespace: backend
    cwd: ./services/api-service
    env_file: ./services/api-service/.env
    env:
      <<: *envs
      PORT: 3001
      API_PREFIX: /v0/api

  - name: auth
    <<: *common
    namespace: backend
    cwd: ./services/auth-service
    env_file: ./services/auth-service/.env
    env:
      <<: *envs
      PORT: 3002
      API_PREFIX: /v0/auth
