.envs: &envs
  PLATFORM_ENV: local
  NPM_CONFIG_SHELL: /bin/bash
  NPM_CONFIG_SCRIPT_SHELL: /bin/bash
  HTTP_HOST: 127.0.0.1
  NODE_ENV: development

  CORS_ORIGIN: '*'

  MONGO_URI: mongodb://localhost:27017/ai-chat-app

  FRONTEND_DOMAIN: localhost
  FRONTEND_PROTOCOL: http

  API_DOMAIN: localhost
  API_PROTOCOL: http

.common: &common
  script: npm
  args: run start
  watch: true
  ignore_watch: [node_modules, dist]
  watch_options:
    followSymlinks: true
  env:
    <<: *envs

apps:
  - name: app
    <<: *common
    watch: false
    namespace: frontend
    cwd: ./clients/web-app
    env:
      <<: *envs
      PORT: 3000
      # REACT_APP_API_BASE_URL: http://localhost
      # REACT_APP_API_PREFIX: /v0/api
      # REACT_APP_AUTH_PREFIX: /v0/auth

  - name: api
    <<: *common
    namespace: backend
    cwd: ./services/api-service
    env:
      <<: *envs
      PORT: 3001
      API_PREFIX: /v0/api

  - name: auth
    <<: *common
    namespace: backend
    cwd: ./services/auth-service
    env:
      <<: *envs
      PORT: 3002
      API_PREFIX: /v0/auth
